services:
  php:
    image: php:8.0-apache
    build: .
    volumes:
      - '.:/var/www/html'
    ports:
      - "8080:80"
    networks:
      - my_network

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - './pcdb:/var/lib/mysql'
    environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ROOT_HOST: localhost
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: userpassword
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge