version: '3.8'
services:
  php:
    image: php:8.0-apache
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - my_network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge